### ISSUE TITLE
How about videos?

### ISSUE THREAD

**Issue by xraisen** [rudiservo/pfsense_storeid#1]
Hi,

Awesome technique you have there! It is the only working cache with 100% hit on steam. But I want to ask, if its possible if you can cache the videos. Do you have any ideas?

Regards!

**Comment by rudiservo** [comment]
I answered in #3
I will be trying to put something new inside OpnSense directly, no more trying to hack stuff, it will take a of time and I dont expect to have it done before the end of this year.
Advantages on OpnSense are php7.1, maybe 7.2, that means a lot more performance then ruby, python or php5.6, also Phalcon framework will make it easier to do new developments.

**Comment by elico** [comment]
I have a ready to use youtube caching service at:
http://ngtech.co.il/static/ytgv-predictor/

If someone wan't to install it (free) let me know.

**Comment by xraisen** [comment]
> I have a ready to use youtube caching service at:
> http://ngtech.co.il/static/ytgv-predictor/
> 
> If someone wan't to install it (free) let me know.

Sure man! I would love to try this out. Any guides?

**Comment by elico** [comment]
@xraisen Bump this issue if I am not responding in a week.
The http://ngtech.co.il/static/ytgv-predictor/example.tar.xz
File should contain a basic installation script.
I Would probably write one in the https://wiki,squid-cache.org/
